/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as UsersRouteImport } from './routes/users'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as SellersRouteImport } from './routes/sellers'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImportsRouteImport } from './routes/imports'
import { Route as ExternalListingsRouteImport } from './routes/external-listings'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as IndexRouteImport } from './routes/index'

const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SellersRoute = SellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportsRoute = ImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => rootRouteImport,
} as any)
const ExternalListingsRoute = ExternalListingsRouteImport.update({
  id: '/external-listings',
  path: '/external-listings',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conversations': typeof ConversationsRoute
  '/documents': typeof DocumentsRoute
  '/external-listings': typeof ExternalListingsRoute
  '/imports': typeof ImportsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/quotes': typeof QuotesRoute
  '/sellers': typeof SellersRoute
  '/statistics': typeof StatisticsRoute
  '/users': typeof UsersRoute
  '/vehicles': typeof VehiclesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conversations': typeof ConversationsRoute
  '/documents': typeof DocumentsRoute
  '/external-listings': typeof ExternalListingsRoute
  '/imports': typeof ImportsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/quotes': typeof QuotesRoute
  '/sellers': typeof SellersRoute
  '/statistics': typeof StatisticsRoute
  '/users': typeof UsersRoute
  '/vehicles': typeof VehiclesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conversations': typeof ConversationsRoute
  '/documents': typeof DocumentsRoute
  '/external-listings': typeof ExternalListingsRoute
  '/imports': typeof ImportsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/quotes': typeof QuotesRoute
  '/sellers': typeof SellersRoute
  '/statistics': typeof StatisticsRoute
  '/users': typeof UsersRoute
  '/vehicles': typeof VehiclesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conversations'
    | '/documents'
    | '/external-listings'
    | '/imports'
    | '/login'
    | '/notifications'
    | '/quotes'
    | '/sellers'
    | '/statistics'
    | '/users'
    | '/vehicles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conversations'
    | '/documents'
    | '/external-listings'
    | '/imports'
    | '/login'
    | '/notifications'
    | '/quotes'
    | '/sellers'
    | '/statistics'
    | '/users'
    | '/vehicles'
  id:
    | '__root__'
    | '/'
    | '/conversations'
    | '/documents'
    | '/external-listings'
    | '/imports'
    | '/login'
    | '/notifications'
    | '/quotes'
    | '/sellers'
    | '/statistics'
    | '/users'
    | '/vehicles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConversationsRoute: typeof ConversationsRoute
  DocumentsRoute: typeof DocumentsRoute
  ExternalListingsRoute: typeof ExternalListingsRoute
  ImportsRoute: typeof ImportsRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  QuotesRoute: typeof QuotesRoute
  SellersRoute: typeof SellersRoute
  StatisticsRoute: typeof StatisticsRoute
  UsersRoute: typeof UsersRoute
  VehiclesRoute: typeof VehiclesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sellers': {
      id: '/sellers'
      path: '/sellers'
      fullPath: '/sellers'
      preLoaderRoute: typeof SellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imports': {
      id: '/imports'
      path: '/imports'
      fullPath: '/imports'
      preLoaderRoute: typeof ImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/external-listings': {
      id: '/external-listings'
      path: '/external-listings'
      fullPath: '/external-listings'
      preLoaderRoute: typeof ExternalListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConversationsRoute: ConversationsRoute,
  DocumentsRoute: DocumentsRoute,
  ExternalListingsRoute: ExternalListingsRoute,
  ImportsRoute: ImportsRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  QuotesRoute: QuotesRoute,
  SellersRoute: SellersRoute,
  StatisticsRoute: StatisticsRoute,
  UsersRoute: UsersRoute,
  VehiclesRoute: VehiclesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
