/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as SellersRouteImport } from './routes/sellers'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as ImportsRouteImport } from './routes/imports'
import { Route as ExternalListingsRouteImport } from './routes/external-listings'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReservationsIndexRouteImport } from './routes/reservations.index'
import { Route as ReservationsIdRouteImport } from './routes/reservations.$id'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SellersRoute = SellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportsRoute = ImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => rootRouteImport,
} as any)
const ExternalListingsRoute = ExternalListingsRouteImport.update({
  id: '/external-listings',
  path: '/external-listings',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsIndexRoute = ReservationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReservationsRoute,
} as any)
const ReservationsIdRoute = ReservationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReservationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conversations': typeof ConversationsRoute
  '/documents': typeof DocumentsRoute
  '/external-listings': typeof ExternalListingsRoute
  '/imports': typeof ImportsRoute
  '/listings': typeof ListingsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/reservations': typeof ReservationsRouteWithChildren
  '/sellers': typeof SellersRoute
  '/statistics': typeof StatisticsRoute
  '/users': typeof UsersRoute
  '/reservations/$id': typeof ReservationsIdRoute
  '/reservations/': typeof ReservationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conversations': typeof ConversationsRoute
  '/documents': typeof DocumentsRoute
  '/external-listings': typeof ExternalListingsRoute
  '/imports': typeof ImportsRoute
  '/listings': typeof ListingsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/sellers': typeof SellersRoute
  '/statistics': typeof StatisticsRoute
  '/users': typeof UsersRoute
  '/reservations/$id': typeof ReservationsIdRoute
  '/reservations': typeof ReservationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conversations': typeof ConversationsRoute
  '/documents': typeof DocumentsRoute
  '/external-listings': typeof ExternalListingsRoute
  '/imports': typeof ImportsRoute
  '/listings': typeof ListingsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/reservations': typeof ReservationsRouteWithChildren
  '/sellers': typeof SellersRoute
  '/statistics': typeof StatisticsRoute
  '/users': typeof UsersRoute
  '/reservations/$id': typeof ReservationsIdRoute
  '/reservations/': typeof ReservationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conversations'
    | '/documents'
    | '/external-listings'
    | '/imports'
    | '/listings'
    | '/login'
    | '/notifications'
    | '/reservations'
    | '/sellers'
    | '/statistics'
    | '/users'
    | '/reservations/$id'
    | '/reservations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conversations'
    | '/documents'
    | '/external-listings'
    | '/imports'
    | '/listings'
    | '/login'
    | '/notifications'
    | '/sellers'
    | '/statistics'
    | '/users'
    | '/reservations/$id'
    | '/reservations'
  id:
    | '__root__'
    | '/'
    | '/conversations'
    | '/documents'
    | '/external-listings'
    | '/imports'
    | '/listings'
    | '/login'
    | '/notifications'
    | '/reservations'
    | '/sellers'
    | '/statistics'
    | '/users'
    | '/reservations/$id'
    | '/reservations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConversationsRoute: typeof ConversationsRoute
  DocumentsRoute: typeof DocumentsRoute
  ExternalListingsRoute: typeof ExternalListingsRoute
  ImportsRoute: typeof ImportsRoute
  ListingsRoute: typeof ListingsRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ReservationsRoute: typeof ReservationsRouteWithChildren
  SellersRoute: typeof SellersRoute
  StatisticsRoute: typeof StatisticsRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sellers': {
      id: '/sellers'
      path: '/sellers'
      fullPath: '/sellers'
      preLoaderRoute: typeof SellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imports': {
      id: '/imports'
      path: '/imports'
      fullPath: '/imports'
      preLoaderRoute: typeof ImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/external-listings': {
      id: '/external-listings'
      path: '/external-listings'
      fullPath: '/external-listings'
      preLoaderRoute: typeof ExternalListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations/': {
      id: '/reservations/'
      path: '/'
      fullPath: '/reservations/'
      preLoaderRoute: typeof ReservationsIndexRouteImport
      parentRoute: typeof ReservationsRoute
    }
    '/reservations/$id': {
      id: '/reservations/$id'
      path: '/$id'
      fullPath: '/reservations/$id'
      preLoaderRoute: typeof ReservationsIdRouteImport
      parentRoute: typeof ReservationsRoute
    }
  }
}

interface ReservationsRouteChildren {
  ReservationsIdRoute: typeof ReservationsIdRoute
  ReservationsIndexRoute: typeof ReservationsIndexRoute
}

const ReservationsRouteChildren: ReservationsRouteChildren = {
  ReservationsIdRoute: ReservationsIdRoute,
  ReservationsIndexRoute: ReservationsIndexRoute,
}

const ReservationsRouteWithChildren = ReservationsRoute._addFileChildren(
  ReservationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConversationsRoute: ConversationsRoute,
  DocumentsRoute: DocumentsRoute,
  ExternalListingsRoute: ExternalListingsRoute,
  ImportsRoute: ImportsRoute,
  ListingsRoute: ListingsRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ReservationsRoute: ReservationsRouteWithChildren,
  SellersRoute: SellersRoute,
  StatisticsRoute: StatisticsRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
